---
title: "M&M ANOVA"
output: html_document
---

# Trick or Treat: Using ANOVA to help your kids get the most candy

```{r echo = FALSE}
# enter your data
type.mm <- c()
number.mm <- c()
blue.mm <- c()

# make a data frame
mm.data <- 
```


```{r echo = FALSE, results = FALSE}
# boxplot of m&ms by type
library(package = "tidyverse")
mm.data %>%
  ggplot(aes(x = , y = , fill = type.mm)) +
  geom_jitter() +
  geom_boxplot() +
  scale_fill_brewer(palette = "", guide = FALSE) +
  labs(x = "M & M type", y = "Number of pieces per package",
       subtitle = "")
  theme_

# descriptive statistics
library(package = "tableone")
mm.table <- CreateTableOne(data = ,
                           strata = "",
                           vars = c(""))
print(mm.table)


```


```{r echo = FALSE, results = FALSE}
# density plot by groups to check normality
mm.data %>%
  ggplot(aes(x = number.mm)) + 
  geom_density(aes(fill = type.mm)) + 
  facet_wrap(~ type.mm) + 
  scale_fill_brewer(palette = "", guide = FALSE) +
  theme_ 
```

```{r echo = FALSE, results = FALSE}
# use Levene in car package to check homogeneity of variances
library(package = "car")
leveneTest(y = number.mm ~ type.mm, data = mm.data)
```



```{r echo = FALSE, results = FALSE}
# ANOVA of mean mms by mm type
number.by.type <- oneway.test(formula = pieces ~ type,
                              data = mm.data,
                              var.equal = TRUE)
number.by.type
```


```{r echo = FALSE, results = FALSE}
# Bonferroni post-hoc test
bonf.mms <- pairwise.t.test(x = mm.data$number.mm,
                            g = mm.data$type.mm,
                            p.adj = "bonf")
bonf.mms
```



```{r echo = FALSE, results = FALSE}
# figure out the order of categories for planned comparisons
levels(x = mm.data$type.mm)
```

```{r echo = FALSE, results = FALSE}
# write a contrast to compare plain to combined peanut & caramel
contrast1 <- c()
```

```{r echo = FALSE, results = FALSE}
# link the contrast to the candy type variable

```

```{r echo = FALSE, results = FALSE}
# re-run the model using aov() 
num.by.type.aov <- aov(formula = number.mm ~ type.mm, 
            data = mm.data)

# apply the contrasts to the anova object num.by.type.aov
# give the contrast a good descriptive name of "Plain vs. others"
plain.vs.other.contr <- summary.aov(object = num.by.type.aov,
                                 split = list(DEGREE = list("Plain vs. others" = 1)))
plain.vs.other.contr
```

```{r echo = FALSE, results = FALSE}
# examine the means for the combined groups
# recode and compute the means for high school and college groups
# the labels should be in the order of the categories as you found
# with the levels code above
mm.data %>%
  mutate(type.mm = factor(x = type.mm, labels = c("peanut & caramel",
                                                "peanut & caramel", "plain"))) %>% 
  group_by(type.mm) %>%
  summarize(m.num.candies = mean(x = number.mm),
            sd.num.candies = sd(x = number.mm))
```

## Study results 



```{r echo = FALSE}

```

```{r echo = FALSE}

```